package com.keqiaokeji.tezizai.common.dbmapper.mc.domain;

public class McMenuTableInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.menu_table_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String menuTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.table_code
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String tableCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.table_content
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String tableContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.status
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.corp_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String corpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.record_status
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.create_user_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.create_time
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.last_modify_user_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private String lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_table_info.last_modify_time
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    private Long lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.menu_table_id
     *
     * @return the value of mc_menu_table_info.menu_table_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getMenuTableId() {
        return menuTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.menu_table_id
     *
     * @param menuTableId the value for mc_menu_table_info.menu_table_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setMenuTableId(String menuTableId) {
        this.menuTableId = menuTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.table_code
     *
     * @return the value of mc_menu_table_info.table_code
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getTableCode() {
        return tableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.table_code
     *
     * @param tableCode the value for mc_menu_table_info.table_code
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setTableCode(String tableCode) {
        this.tableCode = tableCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.table_content
     *
     * @return the value of mc_menu_table_info.table_content
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getTableContent() {
        return tableContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.table_content
     *
     * @param tableContent the value for mc_menu_table_info.table_content
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setTableContent(String tableContent) {
        this.tableContent = tableContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.status
     *
     * @return the value of mc_menu_table_info.status
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.status
     *
     * @param status the value for mc_menu_table_info.status
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.corp_id
     *
     * @return the value of mc_menu_table_info.corp_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.corp_id
     *
     * @param corpId the value for mc_menu_table_info.corp_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.record_status
     *
     * @return the value of mc_menu_table_info.record_status
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.record_status
     *
     * @param recordStatus the value for mc_menu_table_info.record_status
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.create_user_id
     *
     * @return the value of mc_menu_table_info.create_user_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.create_user_id
     *
     * @param createUserId the value for mc_menu_table_info.create_user_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.create_time
     *
     * @return the value of mc_menu_table_info.create_time
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.create_time
     *
     * @param createTime the value for mc_menu_table_info.create_time
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.last_modify_user_id
     *
     * @return the value of mc_menu_table_info.last_modify_user_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.last_modify_user_id
     *
     * @param lastModifyUserId the value for mc_menu_table_info.last_modify_user_id
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_table_info.last_modify_time
     *
     * @return the value of mc_menu_table_info.last_modify_time
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_table_info.last_modify_time
     *
     * @param lastModifyTime the value for mc_menu_table_info.last_modify_time
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}