package com.keqiaokeji.tezizai.common.dbmapper.mc.domain;

public class McMenuListInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_list_info_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuListInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_table_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_type_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_type_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.price_real
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Integer priceReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.price_favorable
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Integer priceFavorable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.picture_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_unit
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.menu_num
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Integer menuNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.corp_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String corpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.record_status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.create_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.create_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.last_modify_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_list_info.last_modify_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Long lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_list_info_id
     *
     * @return the value of mc_menu_list_info.menu_list_info_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuListInfoId() {
        return menuListInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_list_info_id
     *
     * @param menuListInfoId the value for mc_menu_list_info.menu_list_info_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuListInfoId(String menuListInfoId) {
        this.menuListInfoId = menuListInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_table_id
     *
     * @return the value of mc_menu_list_info.menu_table_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuTableId() {
        return menuTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_table_id
     *
     * @param menuTableId the value for mc_menu_list_info.menu_table_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuTableId(String menuTableId) {
        this.menuTableId = menuTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_id
     *
     * @return the value of mc_menu_list_info.menu_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_id
     *
     * @param menuId the value for mc_menu_list_info.menu_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_name
     *
     * @return the value of mc_menu_list_info.menu_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_name
     *
     * @param menuName the value for mc_menu_list_info.menu_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_type_id
     *
     * @return the value of mc_menu_list_info.menu_type_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuTypeId() {
        return menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_type_id
     *
     * @param menuTypeId the value for mc_menu_list_info.menu_type_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuTypeId(String menuTypeId) {
        this.menuTypeId = menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_type_name
     *
     * @return the value of mc_menu_list_info.menu_type_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuTypeName() {
        return menuTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_type_name
     *
     * @param menuTypeName the value for mc_menu_list_info.menu_type_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuTypeName(String menuTypeName) {
        this.menuTypeName = menuTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.price_real
     *
     * @return the value of mc_menu_list_info.price_real
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Integer getPriceReal() {
        return priceReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.price_real
     *
     * @param priceReal the value for mc_menu_list_info.price_real
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setPriceReal(Integer priceReal) {
        this.priceReal = priceReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.price_favorable
     *
     * @return the value of mc_menu_list_info.price_favorable
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Integer getPriceFavorable() {
        return priceFavorable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.price_favorable
     *
     * @param priceFavorable the value for mc_menu_list_info.price_favorable
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setPriceFavorable(Integer priceFavorable) {
        this.priceFavorable = priceFavorable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.picture_id
     *
     * @return the value of mc_menu_list_info.picture_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.picture_id
     *
     * @param pictureId the value for mc_menu_list_info.picture_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setPictureId(String pictureId) {
        this.pictureId = pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_unit
     *
     * @return the value of mc_menu_list_info.menu_unit
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuUnit() {
        return menuUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_unit
     *
     * @param menuUnit the value for mc_menu_list_info.menu_unit
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuUnit(String menuUnit) {
        this.menuUnit = menuUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.menu_num
     *
     * @return the value of mc_menu_list_info.menu_num
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Integer getMenuNum() {
        return menuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.menu_num
     *
     * @param menuNum the value for mc_menu_list_info.menu_num
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuNum(Integer menuNum) {
        this.menuNum = menuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.status
     *
     * @return the value of mc_menu_list_info.status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.status
     *
     * @param status the value for mc_menu_list_info.status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.corp_id
     *
     * @return the value of mc_menu_list_info.corp_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.corp_id
     *
     * @param corpId the value for mc_menu_list_info.corp_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.record_status
     *
     * @return the value of mc_menu_list_info.record_status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.record_status
     *
     * @param recordStatus the value for mc_menu_list_info.record_status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.create_user_id
     *
     * @return the value of mc_menu_list_info.create_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.create_user_id
     *
     * @param createUserId the value for mc_menu_list_info.create_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.create_time
     *
     * @return the value of mc_menu_list_info.create_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.create_time
     *
     * @param createTime the value for mc_menu_list_info.create_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.last_modify_user_id
     *
     * @return the value of mc_menu_list_info.last_modify_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.last_modify_user_id
     *
     * @param lastModifyUserId the value for mc_menu_list_info.last_modify_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_list_info.last_modify_time
     *
     * @return the value of mc_menu_list_info.last_modify_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_list_info.last_modify_time
     *
     * @param lastModifyTime the value for mc_menu_list_info.last_modify_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}