package com.keqiaokeji.tezizai.common.dbmapper.mc.domain;

import java.util.ArrayList;
import java.util.List;

public class McMenuListInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public McMenuListInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuRecordIdIsNull() {
            addCriterion("menu_record_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdIsNotNull() {
            addCriterion("menu_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdEqualTo(String value) {
            addCriterion("menu_record_id =", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdNotEqualTo(String value) {
            addCriterion("menu_record_id <>", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdGreaterThan(String value) {
            addCriterion("menu_record_id >", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("menu_record_id >=", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdLessThan(String value) {
            addCriterion("menu_record_id <", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdLessThanOrEqualTo(String value) {
            addCriterion("menu_record_id <=", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdLike(String value) {
            addCriterion("menu_record_id like", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdNotLike(String value) {
            addCriterion("menu_record_id not like", value, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdIn(List<String> values) {
            addCriterion("menu_record_id in", values, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdNotIn(List<String> values) {
            addCriterion("menu_record_id not in", values, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdBetween(String value1, String value2) {
            addCriterion("menu_record_id between", value1, value2, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuRecordIdNotBetween(String value1, String value2) {
            addCriterion("menu_record_id not between", value1, value2, "menuRecordId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdIsNull() {
            addCriterion("menu_list_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuListIdIsNotNull() {
            addCriterion("menu_list_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuListIdEqualTo(String value) {
            addCriterion("menu_list_id =", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdNotEqualTo(String value) {
            addCriterion("menu_list_id <>", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdGreaterThan(String value) {
            addCriterion("menu_list_id >", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdGreaterThanOrEqualTo(String value) {
            addCriterion("menu_list_id >=", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdLessThan(String value) {
            addCriterion("menu_list_id <", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdLessThanOrEqualTo(String value) {
            addCriterion("menu_list_id <=", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdLike(String value) {
            addCriterion("menu_list_id like", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdNotLike(String value) {
            addCriterion("menu_list_id not like", value, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdIn(List<String> values) {
            addCriterion("menu_list_id in", values, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdNotIn(List<String> values) {
            addCriterion("menu_list_id not in", values, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdBetween(String value1, String value2) {
            addCriterion("menu_list_id between", value1, value2, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuListIdNotBetween(String value1, String value2) {
            addCriterion("menu_list_id not between", value1, value2, "menuListId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("menu_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(String value) {
            addCriterion("menu_id =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(String value) {
            addCriterion("menu_id <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(String value) {
            addCriterion("menu_id >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(String value) {
            addCriterion("menu_id >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(String value) {
            addCriterion("menu_id <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(String value) {
            addCriterion("menu_id <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLike(String value) {
            addCriterion("menu_id like", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotLike(String value) {
            addCriterion("menu_id not like", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<String> values) {
            addCriterion("menu_id in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<String> values) {
            addCriterion("menu_id not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(String value1, String value2) {
            addCriterion("menu_id between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(String value1, String value2) {
            addCriterion("menu_id not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("menu_name is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("menu_name is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("menu_name =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("menu_name <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("menu_name >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("menu_name >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("menu_name <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("menu_name <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("menu_name like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("menu_name not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("menu_name in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("menu_name not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("menu_name between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("menu_name not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andPriceRealIsNull() {
            addCriterion("price_real is null");
            return (Criteria) this;
        }

        public Criteria andPriceRealIsNotNull() {
            addCriterion("price_real is not null");
            return (Criteria) this;
        }

        public Criteria andPriceRealEqualTo(Integer value) {
            addCriterion("price_real =", value, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealNotEqualTo(Integer value) {
            addCriterion("price_real <>", value, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealGreaterThan(Integer value) {
            addCriterion("price_real >", value, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_real >=", value, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealLessThan(Integer value) {
            addCriterion("price_real <", value, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealLessThanOrEqualTo(Integer value) {
            addCriterion("price_real <=", value, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealIn(List<Integer> values) {
            addCriterion("price_real in", values, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealNotIn(List<Integer> values) {
            addCriterion("price_real not in", values, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealBetween(Integer value1, Integer value2) {
            addCriterion("price_real between", value1, value2, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceRealNotBetween(Integer value1, Integer value2) {
            addCriterion("price_real not between", value1, value2, "priceReal");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableIsNull() {
            addCriterion("price_favorable is null");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableIsNotNull() {
            addCriterion("price_favorable is not null");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableEqualTo(Integer value) {
            addCriterion("price_favorable =", value, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableNotEqualTo(Integer value) {
            addCriterion("price_favorable <>", value, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableGreaterThan(Integer value) {
            addCriterion("price_favorable >", value, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_favorable >=", value, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableLessThan(Integer value) {
            addCriterion("price_favorable <", value, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableLessThanOrEqualTo(Integer value) {
            addCriterion("price_favorable <=", value, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableIn(List<Integer> values) {
            addCriterion("price_favorable in", values, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableNotIn(List<Integer> values) {
            addCriterion("price_favorable not in", values, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableBetween(Integer value1, Integer value2) {
            addCriterion("price_favorable between", value1, value2, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPriceFavorableNotBetween(Integer value1, Integer value2) {
            addCriterion("price_favorable not between", value1, value2, "priceFavorable");
            return (Criteria) this;
        }

        public Criteria andPictureIdIsNull() {
            addCriterion("picture_id is null");
            return (Criteria) this;
        }

        public Criteria andPictureIdIsNotNull() {
            addCriterion("picture_id is not null");
            return (Criteria) this;
        }

        public Criteria andPictureIdEqualTo(String value) {
            addCriterion("picture_id =", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdNotEqualTo(String value) {
            addCriterion("picture_id <>", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdGreaterThan(String value) {
            addCriterion("picture_id >", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdGreaterThanOrEqualTo(String value) {
            addCriterion("picture_id >=", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdLessThan(String value) {
            addCriterion("picture_id <", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdLessThanOrEqualTo(String value) {
            addCriterion("picture_id <=", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdLike(String value) {
            addCriterion("picture_id like", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdNotLike(String value) {
            addCriterion("picture_id not like", value, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdIn(List<String> values) {
            addCriterion("picture_id in", values, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdNotIn(List<String> values) {
            addCriterion("picture_id not in", values, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdBetween(String value1, String value2) {
            addCriterion("picture_id between", value1, value2, "pictureId");
            return (Criteria) this;
        }

        public Criteria andPictureIdNotBetween(String value1, String value2) {
            addCriterion("picture_id not between", value1, value2, "pictureId");
            return (Criteria) this;
        }

        public Criteria andMenuUnitIsNull() {
            addCriterion("menu_unit is null");
            return (Criteria) this;
        }

        public Criteria andMenuUnitIsNotNull() {
            addCriterion("menu_unit is not null");
            return (Criteria) this;
        }

        public Criteria andMenuUnitEqualTo(String value) {
            addCriterion("menu_unit =", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitNotEqualTo(String value) {
            addCriterion("menu_unit <>", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitGreaterThan(String value) {
            addCriterion("menu_unit >", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitGreaterThanOrEqualTo(String value) {
            addCriterion("menu_unit >=", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitLessThan(String value) {
            addCriterion("menu_unit <", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitLessThanOrEqualTo(String value) {
            addCriterion("menu_unit <=", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitLike(String value) {
            addCriterion("menu_unit like", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitNotLike(String value) {
            addCriterion("menu_unit not like", value, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitIn(List<String> values) {
            addCriterion("menu_unit in", values, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitNotIn(List<String> values) {
            addCriterion("menu_unit not in", values, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitBetween(String value1, String value2) {
            addCriterion("menu_unit between", value1, value2, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuUnitNotBetween(String value1, String value2) {
            addCriterion("menu_unit not between", value1, value2, "menuUnit");
            return (Criteria) this;
        }

        public Criteria andMenuNumIsNull() {
            addCriterion("menu_num is null");
            return (Criteria) this;
        }

        public Criteria andMenuNumIsNotNull() {
            addCriterion("menu_num is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNumEqualTo(String value) {
            addCriterion("menu_num =", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumNotEqualTo(String value) {
            addCriterion("menu_num <>", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumGreaterThan(String value) {
            addCriterion("menu_num >", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumGreaterThanOrEqualTo(String value) {
            addCriterion("menu_num >=", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumLessThan(String value) {
            addCriterion("menu_num <", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumLessThanOrEqualTo(String value) {
            addCriterion("menu_num <=", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumLike(String value) {
            addCriterion("menu_num like", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumNotLike(String value) {
            addCriterion("menu_num not like", value, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumIn(List<String> values) {
            addCriterion("menu_num in", values, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumNotIn(List<String> values) {
            addCriterion("menu_num not in", values, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumBetween(String value1, String value2) {
            addCriterion("menu_num between", value1, value2, "menuNum");
            return (Criteria) this;
        }

        public Criteria andMenuNumNotBetween(String value1, String value2) {
            addCriterion("menu_num not between", value1, value2, "menuNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCorpIdIsNull() {
            addCriterion("corp_id is null");
            return (Criteria) this;
        }

        public Criteria andCorpIdIsNotNull() {
            addCriterion("corp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCorpIdEqualTo(String value) {
            addCriterion("corp_id =", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotEqualTo(String value) {
            addCriterion("corp_id <>", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdGreaterThan(String value) {
            addCriterion("corp_id >", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdGreaterThanOrEqualTo(String value) {
            addCriterion("corp_id >=", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdLessThan(String value) {
            addCriterion("corp_id <", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdLessThanOrEqualTo(String value) {
            addCriterion("corp_id <=", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdLike(String value) {
            addCriterion("corp_id like", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotLike(String value) {
            addCriterion("corp_id not like", value, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdIn(List<String> values) {
            addCriterion("corp_id in", values, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotIn(List<String> values) {
            addCriterion("corp_id not in", values, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdBetween(String value1, String value2) {
            addCriterion("corp_id between", value1, value2, "corpId");
            return (Criteria) this;
        }

        public Criteria andCorpIdNotBetween(String value1, String value2) {
            addCriterion("corp_id not between", value1, value2, "corpId");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNull() {
            addCriterion("record_status is null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNotNull() {
            addCriterion("record_status is not null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusEqualTo(String value) {
            addCriterion("record_status =", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotEqualTo(String value) {
            addCriterion("record_status <>", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThan(String value) {
            addCriterion("record_status >", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThanOrEqualTo(String value) {
            addCriterion("record_status >=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThan(String value) {
            addCriterion("record_status <", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThanOrEqualTo(String value) {
            addCriterion("record_status <=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLike(String value) {
            addCriterion("record_status like", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotLike(String value) {
            addCriterion("record_status not like", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIn(List<String> values) {
            addCriterion("record_status in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotIn(List<String> values) {
            addCriterion("record_status not in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusBetween(String value1, String value2) {
            addCriterion("record_status between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotBetween(String value1, String value2) {
            addCriterion("record_status not between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdIsNull() {
            addCriterion("last_modify_user_id is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdIsNotNull() {
            addCriterion("last_modify_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdEqualTo(String value) {
            addCriterion("last_modify_user_id =", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdNotEqualTo(String value) {
            addCriterion("last_modify_user_id <>", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdGreaterThan(String value) {
            addCriterion("last_modify_user_id >", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("last_modify_user_id >=", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdLessThan(String value) {
            addCriterion("last_modify_user_id <", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdLessThanOrEqualTo(String value) {
            addCriterion("last_modify_user_id <=", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdLike(String value) {
            addCriterion("last_modify_user_id like", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdNotLike(String value) {
            addCriterion("last_modify_user_id not like", value, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdIn(List<String> values) {
            addCriterion("last_modify_user_id in", values, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdNotIn(List<String> values) {
            addCriterion("last_modify_user_id not in", values, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdBetween(String value1, String value2) {
            addCriterion("last_modify_user_id between", value1, value2, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyUserIdNotBetween(String value1, String value2) {
            addCriterion("last_modify_user_id not between", value1, value2, "lastModifyUserId");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("last_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("last_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Long value) {
            addCriterion("last_modify_time =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Long value) {
            addCriterion("last_modify_time <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Long value) {
            addCriterion("last_modify_time >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("last_modify_time >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Long value) {
            addCriterion("last_modify_time <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Long value) {
            addCriterion("last_modify_time <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Long> values) {
            addCriterion("last_modify_time in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Long> values) {
            addCriterion("last_modify_time not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Long value1, Long value2) {
            addCriterion("last_modify_time between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Long value1, Long value2) {
            addCriterion("last_modify_time not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 22 10:41:54 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mc_menu_list_info
     *
     * @mbggenerated Sun Jun 22 10:41:54 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}