package com.keqiaokeji.tezizai.common.dbmapper.mc.domain;

public class McMenuTypeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.menu_type_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.menu_type_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String menuTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.menu_type_order
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Integer menuTypeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.corp_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String corpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.record_status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.create_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.create_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.last_modify_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private String lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_menu_type_info.last_modify_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    private Long lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.menu_type_id
     *
     * @return the value of mc_menu_type_info.menu_type_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuTypeId() {
        return menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.menu_type_id
     *
     * @param menuTypeId the value for mc_menu_type_info.menu_type_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuTypeId(String menuTypeId) {
        this.menuTypeId = menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.menu_type_name
     *
     * @return the value of mc_menu_type_info.menu_type_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getMenuTypeName() {
        return menuTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.menu_type_name
     *
     * @param menuTypeName the value for mc_menu_type_info.menu_type_name
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuTypeName(String menuTypeName) {
        this.menuTypeName = menuTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.menu_type_order
     *
     * @return the value of mc_menu_type_info.menu_type_order
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Integer getMenuTypeOrder() {
        return menuTypeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.menu_type_order
     *
     * @param menuTypeOrder the value for mc_menu_type_info.menu_type_order
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setMenuTypeOrder(Integer menuTypeOrder) {
        this.menuTypeOrder = menuTypeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.corp_id
     *
     * @return the value of mc_menu_type_info.corp_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.corp_id
     *
     * @param corpId the value for mc_menu_type_info.corp_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.record_status
     *
     * @return the value of mc_menu_type_info.record_status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.record_status
     *
     * @param recordStatus the value for mc_menu_type_info.record_status
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.create_user_id
     *
     * @return the value of mc_menu_type_info.create_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.create_user_id
     *
     * @param createUserId the value for mc_menu_type_info.create_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.create_time
     *
     * @return the value of mc_menu_type_info.create_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.create_time
     *
     * @param createTime the value for mc_menu_type_info.create_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.last_modify_user_id
     *
     * @return the value of mc_menu_type_info.last_modify_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.last_modify_user_id
     *
     * @param lastModifyUserId the value for mc_menu_type_info.last_modify_user_id
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_menu_type_info.last_modify_time
     *
     * @return the value of mc_menu_type_info.last_modify_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_menu_type_info.last_modify_time
     *
     * @param lastModifyTime the value for mc_menu_type_info.last_modify_time
     *
     * @mbggenerated Sat Jun 28 12:17:52 CST 2014
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}