package com.keqiaokeji.tezizai.common.dbmapper.mc.mapper;

import com.keqiaokeji.tezizai.common.dbmapper.mc.domain.McMenuTypeInfo;
import com.keqiaokeji.tezizai.common.dbmapper.mc.domain.McMenuTypeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface McMenuTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int countByExample(McMenuTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int deleteByExample(McMenuTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int deleteByPrimaryKey(String menuTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int insert(McMenuTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int insertSelective(McMenuTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    List<McMenuTypeInfo> selectByExample(McMenuTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    McMenuTypeInfo selectByPrimaryKey(String menuTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int updateByExampleSelective(@Param("record") McMenuTypeInfo record, @Param("example") McMenuTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int updateByExample(@Param("record") McMenuTypeInfo record, @Param("example") McMenuTypeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int updateByPrimaryKeySelective(McMenuTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_type_info
     *
     * @mbggenerated Mon Jun 09 22:50:49 CST 2014
     */
    int updateByPrimaryKey(McMenuTypeInfo record);
}