package com.keqiaokeji.tezizai.common.dbmapper.mc.mapper;

import com.keqiaokeji.tezizai.common.dbmapper.mc.domain.McMenuTableInfo;
import com.keqiaokeji.tezizai.common.dbmapper.mc.domain.McMenuTableInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface McMenuTableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int countByExample(McMenuTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int deleteByExample(McMenuTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int deleteByPrimaryKey(String menuTableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int insert(McMenuTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int insertSelective(McMenuTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    List<McMenuTableInfo> selectByExample(McMenuTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    McMenuTableInfo selectByPrimaryKey(String menuTableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int updateByExampleSelective(@Param("record") McMenuTableInfo record, @Param("example") McMenuTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int updateByExample(@Param("record") McMenuTableInfo record, @Param("example") McMenuTableInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int updateByPrimaryKeySelective(McMenuTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_menu_table_info
     *
     * @mbggenerated Sun Jun 22 11:39:47 CST 2014
     */
    int updateByPrimaryKey(McMenuTableInfo record);
}